"""Build an EpiABM processed cache one county at a time and merge results.

This is a fault-tolerant wrapper around ``EpiABMDatasetCollection``. It does not
change the EpiABM data generation mechanism; each county is generated by the
same collection class, then rows are merged into one cache bundle.
"""

from __future__ import annotations

import argparse
import csv
import json
import pickle
import sys
import time
import traceback
from pathlib import Path
from typing import Any, Dict, Iterable, List, Tuple

import numpy as np
from omegaconf import OmegaConf

sys.path.append(str(Path(__file__).resolve().parents[2]))

from src.data.epi_abm.dataset import EpiABMDatasetCollection  # noqa: E402
from src.data.epi_abm.simulator_cache import normalize_county_id  # noqa: E402


def _counties_from_csv(path: str) -> List[str]:
    csv_path = Path(path)
    if not csv_path.is_absolute():
        csv_path = Path.cwd() / csv_path
    counties = set()
    with csv_path.open(newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            counties.add(normalize_county_id(row["county"]))
    return sorted(counties)


def _cache_path(output_dir: Path, counties: List[str], date_tag: str, cache_version: str) -> Path:
    county_label = counties[0] if len(counties) == 1 else "multi_" + "_".join(counties[:3])
    if len(counties) > 3:
        county_label = f"{county_label}_plus{len(counties) - 3}"
    return output_dir / f"{county_label}_{date_tag}_{cache_version}.pkl"


def _make_county_split_indices(
    data: Dict[str, np.ndarray],
    *,
    seed: int,
    split: Dict[str, float],
    split_by_requested: str,
) -> Tuple[Dict[str, List[int]], Dict[str, Any]]:
    county_values = np.asarray(data["sim_county_id"])[:, 0, 0]
    row_counties = np.asarray([normalize_county_id(x) for x in county_values])
    counties = np.asarray(sorted(set(row_counties.tolist())))

    if split_by_requested == "county" and counties.size >= 3:
        rng = np.random.RandomState(seed)
        shuffled = counties.copy()
        rng.shuffle(shuffled)
        n_counties = int(shuffled.size)
        n_test = max(1, int(round(n_counties * float(split.get("test", 0.25)))))
        n_val = max(1, int(round(n_counties * float(split.get("val", 0.25)))))
        if n_test + n_val >= n_counties:
            n_test = 1
            n_val = 1
        n_train = n_counties - n_val - n_test
        train_counties = set(shuffled[:n_train].tolist())
        val_counties = set(shuffled[n_train : n_train + n_val].tolist())
        test_counties = set(shuffled[n_train + n_val :].tolist())
        split_indices = {
            "train": np.where(np.isin(row_counties, list(train_counties)))[0].astype(int).tolist(),
            "val": np.where(np.isin(row_counties, list(val_counties)))[0].astype(int).tolist(),
            "test": np.where(np.isin(row_counties, list(test_counties)))[0].astype(int).tolist(),
        }
        return split_indices, {
            "split_by_requested": split_by_requested,
            "split_by_effective": "county",
            "split_seed": int(seed),
            "split_counties": {
                "train": sorted(train_counties),
                "val": sorted(val_counties),
                "test": sorted(test_counties),
            },
        }

    n = int(np.asarray(data["active_entries"]).shape[0])
    rng = np.random.RandomState(seed)
    indices = np.arange(n)
    rng.shuffle(indices)
    n_test = max(1, int(round(n * float(split.get("test", 0.25))))) if n >= 3 else 1
    n_val = max(1, int(round(n * float(split.get("val", 0.25))))) if n >= 3 else 1
    n_train = max(1, n - n_val - n_test)
    split_indices = {
        "train": indices[:n_train].astype(int).tolist(),
        "val": indices[n_train : n_train + n_val].astype(int).tolist(),
        "test": indices[n_train + n_val :].astype(int).tolist(),
    }
    if len(split_indices["test"]) == 0:
        split_indices["test"] = list(split_indices["val"])
    return split_indices, {
        "split_by_requested": split_by_requested,
        "split_by_effective": "episode",
        "split_seed": int(seed),
        "split_counties": {},
    }


def _concat_rows(row_bundles: List[Dict[str, Any]]) -> Dict[str, np.ndarray]:
    merged: Dict[str, np.ndarray] = {}
    keys = row_bundles[0]["data"].keys()
    for key in keys:
        values = [np.asarray(bundle["data"][key]) for bundle in row_bundles]
        if values[0].shape[0] == 1:
            merged[key] = np.concatenate(values, axis=0)
        else:
            merged[key] = values[0]
    return merged


def _build_one_county(
    *,
    base_kwargs: Dict[str, Any],
    county: str,
    global_episode_id: int,
    base_seed: int,
    per_county_dir: Path,
    cache_version: str,
    reuse_existing: bool,
) -> Dict[str, Any]:
    county_dir = per_county_dir / county
    kwargs = dict(base_kwargs)
    kwargs.update(
        {
            "county": county,
            "counties": [county],
            "counties_from_epicf_csv": None,
            "processed_data_dir": str(county_dir),
            "generate_if_missing": True,
            "force_regenerate": not bool(reuse_existing),
            "cache_version": f"{cache_version}_{county}_seed{base_seed + global_episode_id}",
            "seed": int(base_seed + global_episode_id),
        }
    )
    collection = EpiABMDatasetCollection(**kwargs)
    path = collection._cache_path()
    with path.open("rb") as f:
        bundle = pickle.load(f)

    data = {k: np.asarray(v).copy() for k, v in bundle["data"].items()}
    if "sim_episode_id" in data:
        data["sim_episode_id"][:, :, :] = float(global_episode_id)
    if "sim_seed" in data:
        data["sim_seed"][:, :, :] = float(base_seed + global_episode_id)
    episode_actions = {int(global_episode_id): np.asarray(bundle["episode_actions"][0], dtype=np.float32)}
    policy_name = f"{county}:factual"
    return {
        "data": data,
        "episode_actions": episode_actions,
        "policy_name": policy_name,
        "county": county,
        "episode_id": int(global_episode_id),
        "seed": int(base_seed + global_episode_id),
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", required=True)
    parser.add_argument("--epi-root", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--cache-version", required=True)
    parser.add_argument("--per-county-dir", required=True)
    parser.add_argument("--abm-device", default="cpu")
    parser.add_argument("--continue-on-error", action="store_true")
    parser.add_argument("--reuse-existing", action="store_true")
    parser.add_argument("--max-counties", type=int, default=None)
    args = parser.parse_args()

    cfg = OmegaConf.load(args.config)
    OmegaConf.set_struct(cfg, False)
    base_kwargs = OmegaConf.to_container(cfg.dataset, resolve=True)
    base_kwargs.pop("_target_", None)
    base_kwargs["epi_root"] = args.epi_root
    base_kwargs["device"] = args.abm_device
    base_kwargs["generate_if_missing"] = True
    base_kwargs["force_regenerate"] = False
    base_seed = int(base_kwargs.get("seed", 0))
    date_tag = str(base_kwargs.get("date_tag"))
    split = dict(base_kwargs.get("split") or {"val": 0.25, "test": 0.25})
    split_by = str(base_kwargs.get("split_by") or "county").strip().lower()

    if base_kwargs.get("counties"):
        counties = [normalize_county_id(c) for c in base_kwargs["counties"]]
    else:
        counties = _counties_from_csv(str(base_kwargs["counties_from_epicf_csv"]))
    requested_counties = list(counties)
    if args.max_counties is not None:
        counties = counties[: int(args.max_counties)]

    output_dir = Path(args.output_dir)
    per_county_dir = Path(args.per_county_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    per_county_dir.mkdir(parents=True, exist_ok=True)

    started = time.time()
    row_bundles: List[Dict[str, Any]] = []
    failed: List[Dict[str, Any]] = []
    for idx, county in enumerate(counties):
        print(json.dumps({
            "event": "county_build_start",
            "idx": int(idx),
            "county": county,
            "seed": int(base_seed + idx),
        }), flush=True)
        try:
            row_bundle = _build_one_county(
                base_kwargs=base_kwargs,
                county=county,
                global_episode_id=idx,
                base_seed=base_seed,
                per_county_dir=per_county_dir,
                cache_version=args.cache_version,
                reuse_existing=bool(args.reuse_existing),
            )
            row_bundles.append(row_bundle)
            print(json.dumps({
                "event": "county_build_done",
                "idx": int(idx),
                "county": county,
                "n_success": len(row_bundles),
            }), flush=True)
        except Exception as exc:
            item = {
                "idx": int(idx),
                "county": county,
                "seed": int(base_seed + idx),
                "error": repr(exc),
            }
            failed.append(item)
            print(json.dumps({"event": "county_build_failed", **item}), flush=True)
            traceback.print_exc()
            if not args.continue_on_error:
                raise

    if not row_bundles:
        raise RuntimeError("No county cache rows were generated successfully.")

    data = _concat_rows(row_bundles)
    episode_actions: Dict[int, np.ndarray] = {}
    policy_name_by_episode: Dict[str, str] = {}
    policy_names: List[str] = []
    successful_counties: List[str] = []
    for row_bundle in row_bundles:
        episode_actions.update(row_bundle["episode_actions"])
        policy_name_by_episode[str(row_bundle["episode_id"])] = row_bundle["policy_name"]
        policy_names.append(row_bundle["policy_name"])
        successful_counties.append(row_bundle["county"])

    split_indices, split_metadata = _make_county_split_indices(
        data,
        seed=base_seed,
        split=split,
        split_by_requested=split_by,
    )
    metadata = {
        "policy_names": policy_names,
        "num_episodes": len(policy_names),
        "policy_name_by_episode": policy_name_by_episode,
        "counties": successful_counties,
        "requested_counties": requested_counties,
        "failed_counties": failed,
        "behavior_policy_subset": base_kwargs.get("behavior_policy_subset"),
        "action_hold_days": int(base_kwargs.get("action_hold_days", 7)),
        "epi_root": str(base_kwargs.get("epi_root")),
        "date_tag": date_tag,
        "seed": int(base_seed),
        "max_seq_length": int(base_kwargs.get("max_seq_length", 0)),
        "intervention_mode": base_kwargs.get("intervention_mode"),
        "treatment_mode": base_kwargs.get("treatment_mode"),
        "num_random_policies": int(base_kwargs.get("num_random_policies", 0)),
        "build_mode": "per_county_robust",
        "cache_version": args.cache_version,
        "started_at": started,
        "finished_at": time.time(),
        **split_metadata,
    }
    bundle = {
        "data": data,
        "episode_actions": episode_actions,
        "metadata": metadata,
        "split_indices": split_indices,
    }

    path = _cache_path(output_dir, requested_counties, date_tag, args.cache_version)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("wb") as f:
        pickle.dump(bundle, f)
    manifest_path = path.with_suffix(".manifest.json")
    manifest = dict(metadata)
    manifest.update(
        {
            "cache_path": str(path),
            "n_requested": len(requested_counties),
            "n_attempted": len(counties),
            "n_success": len(successful_counties),
            "n_failed": len(failed),
            "split_indices": split_indices,
        }
    )
    manifest_path.write_text(json.dumps(manifest, indent=2, sort_keys=True), encoding="utf-8")
    print(json.dumps({
        "event": "cache_build_done",
        "cache_path": str(path),
        "manifest_path": str(manifest_path),
        "n_success": len(successful_counties),
        "n_failed": len(failed),
        "failed_counties": failed,
    }), flush=True)


if __name__ == "__main__":
    main()
